import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto">
          <div className="leading-relaxed text text-slate-200 antialiased selection:bg-teal-300 selection:text-teal-900">
            <div className = "z-[-10] bg-slate-950 fixed inset-0 bg-[radia-gradient(circle_500px_at_50%_200px,#34a4391,transparent)]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
